### PR TITLE
Project Structure

### PR DESCRIPTION
**Pull request by WhiteBoardDev**
- Yo generated project
- removing extra external scripts which I don't think we need

### CODE REVIEW

**Review by jonatan-ivanov — APPROVED** [review]

**Comment by jonatan-ivanov** [comment]
I checked HuBot out. I feel that we don't really need the whole bot here, I guess two things are necessary:
- Our own set of standalone packages, like these: https://www.npmjs.com/search?q=keywords:hubot-scripts
- Automating installing and running it

**Comment by WhiteBoardDev** [comment]
Based on your comment, it looks like the main feedback point we need to consider is if this bot is meant to be only used as a container to import shared scripts, or do we have embedded scripts within the container.

I'm thinking that we might want to start on the script approach and use this project to import those shared scripts. The reason would be that shared scripts would be consumable by the community and not just by us in this specific bot.

At the end of the project, the bot would simply be a collection of shared script imports and settings for those scripts instead of actually containing business logic.

Thoughts?

**Comment by jonatan-ivanov** [comment]
Yepp, shared scripts FTW! :)

**Comment by srt4** [comment]
@WhiteBoardDev Interpreting your interpretation of @jonatan-ivanov's comment: 

The bot would essentially be a barebones Hubot, and the work we do is to create plugins/extensions of this bot. 

We wouldn't bundle/ship a decorated Hubot. Rather, we'd ship the initialization logic to create a Hubot and import our scripts into it.

Does that sounds right?

**Comment by WhiteBoardDev** [comment]
Yes that ^

So the next step would be deciding how to structure all of these shared modules.

**Pull request merged**
